// Expanded asset database with 200+ assets (symbols/names only - prices fetched LIVE)
export const EXPANDED_ASSETS = [
  // ─── MEGA-CAP TECH (12)
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology', confidence: 85 },
  { symbol: 'NVDA', name: 'NVIDIA Corp', sector: 'Technology', confidence: 87 },
  { symbol: 'MSFT', name: 'Microsoft Corp', sector: 'Technology', confidence: 82 },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology', confidence: 75 },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)', sector: 'Technology', confidence: 75 },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer', confidence: 80 },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Technology', confidence: 70 },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Automotive', confidence: 65 },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology', confidence: 78 },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Software', confidence: 72 },
  { symbol: 'ACHR', name: 'Archer-Daniels Inc.', sector: 'Agriculture', confidence: 68 },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Media', confidence: 79 },

  // ─── MEGA-CAP FINANCE & ENERGY (12)
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Finance', confidence: 81 },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Finance', confidence: 70 },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Finance', confidence: 68 },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Finance', confidence: 72 },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Finance', confidence: 76 },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'Finance', confidence: 69 },
  { symbol: 'XOM', name: 'Exxon Mobil', sector: 'Energy', confidence: 71 },
  { symbol: 'CVX', name: 'Chevron Corp', sector: 'Energy', confidence: 70 },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy', confidence: 68 },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy', confidence: 69 },
  { symbol: 'OKE', name: 'ONEOK Inc.', sector: 'Energy', confidence: 67 },
  { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy', confidence: 66 },

  // ─── HEALTHCARE & PHARMA (12)
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare', confidence: 83 },
  { symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Healthcare', confidence: 82 },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Pharma', confidence: 70 },
  { symbol: 'MRK', name: 'Merck & Co.', sector: 'Pharma', confidence: 74 },
  { symbol: 'AZN', name: 'AstraZeneca', sector: 'Pharma', confidence: 72 },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Pharma', confidence: 85 },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Pharma', confidence: 78 },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Pharma', confidence: 80 },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Healthcare', confidence: 68 },
  { symbol: 'CCI', name: 'Crown Castle', sector: 'Healthcare', confidence: 69 },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Pharma', confidence: 71 },
  { symbol: 'VRTX', name: 'Vertex Pharma', sector: 'Pharma', confidence: 76 },

  // ─── CONSUMER DISCRETIONARY (12)
  { symbol: 'MCD', name: "McDonald's Corp", sector: 'Consumer', confidence: 77 },
  { symbol: 'NKE', name: 'Nike Inc.', sector: 'Consumer', confidence: 65 },
  { symbol: 'SBUX', name: 'Starbucks Corp', sector: 'Consumer', confidence: 70 },
  { symbol: 'TJX', name: 'TJX Companies', sector: 'Retail', confidence: 74 },
  { symbol: 'COST', name: 'Costco Inc.', sector: 'Retail', confidence: 81 },
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Retail', confidence: 76 },
  { symbol: 'HD', name: 'Home Depot', sector: 'Retail', confidence: 78 },
  { symbol: 'LOW', name: "Lowe's Companies", sector: 'Retail', confidence: 75 },
  { symbol: 'ULTA', name: 'Ulta Beauty', sector: 'Retail', confidence: 77 },
  { symbol: 'LULULEMON', name: 'Lululemon Athletica', sector: 'Consumer', confidence: 79 },
  { symbol: 'ORCL', name: 'Oracle Corp', sector: 'Software', confidence: 76 },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Software', confidence: 77 },

  // ─── INDUSTRIAL & MATERIALS (12)
  { symbol: 'GE', name: 'General Electric', sector: 'Industrial', confidence: 73 },
  { symbol: 'BA', name: 'Boeing Inc.', sector: 'Industrial', confidence: 69 },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrial', confidence: 75 },
  { symbol: 'MMM', name: '3M Inc.', sector: 'Industrial', confidence: 68 },
  { symbol: 'ITW', name: 'Illinois Tool Works', sector: 'Industrial', confidence: 72 },
  { symbol: 'AZO', name: 'AutoZone Inc.', sector: 'Retail', confidence: 74 },
  { symbol: 'DAL', name: 'Delta Air Lines', sector: 'Industrial', confidence: 70 },
  { symbol: 'UAL', name: 'United Airlines', sector: 'Industrial', confidence: 69 },
  { symbol: 'LUV', name: 'Southwest Airlines', sector: 'Industrial', confidence: 66 },
  { symbol: 'ALK', name: 'Alaska Air Group', sector: 'Industrial', confidence: 67 },
  { symbol: 'RSG', name: 'Republic Services', sector: 'Industrial', confidence: 73 },
  { symbol: 'WM', name: 'Waste Management', sector: 'Industrial', confidence: 74 },

  // ─── UTILITIES & TELECOM (10)
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities', confidence: 70 },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities', confidence: 69 },
  { symbol: 'SO', name: 'Southern Company', sector: 'Utilities', confidence: 68 },
  { symbol: 'EXC', name: 'Exelon Corp.', sector: 'Utilities', confidence: 66 },
  { symbol: 'VZ', name: 'Verizon Communications', sector: 'Telecom', confidence: 67 },
  { symbol: 'T', name: 'AT&T Inc.', sector: 'Telecom', confidence: 65 },
  { symbol: 'TMUS', name: 'T-Mobile US', sector: 'Telecom', confidence: 72 },
  { symbol: 'PCG', name: 'PG&E Corp.', sector: 'Utilities', confidence: 64 },
  { symbol: 'AEP', name: 'American Electric', sector: 'Utilities', confidence: 68 },
  { symbol: 'SRE', name: 'Sempra Energy', sector: 'Utilities', confidence: 67 },

  // ─── REAL ESTATE & LOGISTICS (10)
  { symbol: 'DLR', name: 'Digital Realty', sector: 'Real Estate', confidence: 74 },
  { symbol: 'EQIX', name: 'Equinix Inc.', sector: 'Real Estate', confidence: 76 },
  { symbol: 'WELL', name: 'Welltower Inc.', sector: 'Real Estate', confidence: 70 },
  { symbol: 'PLD', name: 'Prologis Inc.', sector: 'Real Estate', confidence: 73 },
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate', confidence: 75 },
  { symbol: 'FDX', name: 'FedEx Corp.', sector: 'Logistics', confidence: 77 },
  { symbol: 'UPS', name: 'United Parcel Svc', sector: 'Logistics', confidence: 71 },
  { symbol: 'XPO', name: 'XPO Inc.', sector: 'Logistics', confidence: 69 },
  { symbol: 'LAD', name: 'Ladder Capital', sector: 'Real Estate', confidence: 62 },
  { symbol: 'REXR', name: 'Rexford Industrial', sector: 'Real Estate', confidence: 68 },

  // ─── FOOD & BEVERAGE (10)
  { symbol: 'KO', name: 'Coca-Cola Company', sector: 'Consumer', confidence: 70 },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer', confidence: 73 },
  { symbol: 'MO', name: 'Altria Group', sector: 'Consumer', confidence: 66 },
  { symbol: 'PM', name: 'Philip Morris Intl', sector: 'Consumer', confidence: 68 },
  { symbol: 'BUD', name: 'Anheuser-Busch', sector: 'Consumer', confidence: 67 },
  { symbol: 'DEO', name: 'Diageo PLC', sector: 'Consumer', confidence: 68 },
  { symbol: 'MDLZ', name: 'Mondelez Intl', sector: 'Consumer', confidence: 71 },
  { symbol: 'GIS', name: 'General Mills', sector: 'Consumer', confidence: 68 },
  { symbol: 'K', name: 'Kellogg Company', sector: 'Consumer', confidence: 65 },
  { symbol: 'SJM', name: 'Smucker Inc.', sector: 'Consumer', confidence: 69 },

  // ─── ETFs (20)
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF', sector: 'ETF', confidence: 78 },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', sector: 'ETF', confidence: 80 },
  { symbol: 'DIA', name: 'SPDR Dow Jones ETF', sector: 'ETF', confidence: 72 },
  { symbol: 'IWM', name: 'iShares Russell 2000', sector: 'ETF', confidence: 70 },
  { symbol: 'XLE', name: 'Energy Select ETF', sector: 'ETF', confidence: 65 },
  { symbol: 'XLF', name: 'Financial Select ETF', sector: 'ETF', confidence: 69 },
  { symbol: 'XLK', name: 'Tech Select ETF', sector: 'ETF', confidence: 76 },
  { symbol: 'XLV', name: 'Health Care Select ETF', sector: 'ETF', confidence: 74 },
  { symbol: 'XLI', name: 'Industrial Select ETF', sector: 'ETF', confidence: 72 },
  { symbol: 'XLRE', name: 'Real Estate Select ETF', sector: 'ETF', confidence: 73 },
  { symbol: 'XLY', name: 'Consumer Disc ETF', sector: 'ETF', confidence: 75 },
  { symbol: 'XLP', name: 'Consumer Staples ETF', sector: 'ETF', confidence: 70 },
  { symbol: 'GLD', name: 'SPDR Gold Shares', sector: 'Commodity ETF', confidence: 68 },
  { symbol: 'TLT', name: 'iShares 20+ Yr Tsy', sector: 'Bond ETF', confidence: 66 },
  { symbol: 'LQD', name: 'iShares Inv Grd Corp', sector: 'Bond ETF', confidence: 67 },
  { symbol: 'HYG', name: 'iShares High Yield', sector: 'Bond ETF', confidence: 68 },
  { symbol: 'VTI', name: 'Vanguard Total Stock', sector: 'ETF', confidence: 77 },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', sector: 'ETF', confidence: 72 },
  { symbol: 'ARKF', name: 'ARK Fintech ETF', sector: 'ETF', confidence: 70 },
  { symbol: 'VOO', name: 'Vanguard S&P 500', sector: 'ETF', confidence: 78 },

  // ─── CRYPTO (25)
  { symbol: 'BTC', name: 'Bitcoin', sector: 'Crypto', confidence: 76 },
  { symbol: 'ETH', name: 'Ethereum', sector: 'Crypto', confidence: 74 },
  { symbol: 'SOL', name: 'Solana', sector: 'Crypto', confidence: 72 },
  { symbol: 'XRP', name: 'Ripple', sector: 'Crypto', confidence: 65 },
  { symbol: 'ADA', name: 'Cardano', sector: 'Crypto', confidence: 68 },
  { symbol: 'DOGE', name: 'Dogecoin', sector: 'Crypto', confidence: 64 },
  { symbol: 'MATIC', name: 'Polygon', sector: 'Crypto', confidence: 70 },
  { symbol: 'AVAX', name: 'Avalanche', sector: 'Crypto', confidence: 71 },
  { symbol: 'FTM', name: 'Fantom', sector: 'Crypto', confidence: 69 },
  { symbol: 'LINK', name: 'Chainlink', sector: 'Crypto', confidence: 70 },
  { symbol: 'ARB', name: 'Arbitrum', sector: 'Crypto', confidence: 67 },
  { symbol: 'OP', name: 'Optimism', sector: 'Crypto', confidence: 68 },
  { symbol: 'LDO', name: 'Lido Finance', sector: 'Crypto', confidence: 67 },
  { symbol: 'PEPE', name: 'Pepe', sector: 'Crypto', confidence: 55 },
  { symbol: 'SHIB', name: 'Shiba Inu', sector: 'Crypto', confidence: 60 },
  { symbol: 'UNI', name: 'Uniswap', sector: 'Crypto', confidence: 68 },
  { symbol: 'AAVE', name: 'Aave', sector: 'Crypto', confidence: 71 },
  { symbol: 'CRV', name: 'Curve DAO', sector: 'Crypto', confidence: 62 },
  { symbol: 'MKR', name: 'Maker', sector: 'Crypto', confidence: 70 },
  { symbol: 'SNX', name: 'Synthetix', sector: 'Crypto', confidence: 66 },
  { symbol: 'GRT', name: 'The Graph', sector: 'Crypto', confidence: 65 },
  { symbol: 'ATOM', name: 'Cosmos', sector: 'Crypto', confidence: 67 },
  { symbol: 'NEAR', name: 'Near Protocol', sector: 'Crypto', confidence: 69 },
  { symbol: 'ALGO', name: 'Algorand', sector: 'Crypto', confidence: 65 },
  { symbol: 'FLOW', name: 'Flow', sector: 'Crypto', confidence: 64 },

  // ─── ADDITIONAL US STOCKS (40+)
  { symbol: 'INTC', name: 'Intel Corp.', sector: 'Technology', confidence: 60 },
  { symbol: 'AMD', name: 'Advanced Micro Dev', sector: 'Technology', confidence: 74 },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology', confidence: 72 },
  { symbol: 'MU', name: 'Micron Technology', sector: 'Technology', confidence: 70 },
  { symbol: 'ASML', name: 'ASML Holding NV', sector: 'Technology', confidence: 76 },
  { symbol: 'COIN', name: 'Coinbase Inc.', sector: 'Crypto', confidence: 72 },
  { symbol: 'MSTR', name: 'Microstrategy Inc.', sector: 'Software', confidence: 71 },
  { symbol: 'RIOT', name: 'Riot Platform Inc.', sector: 'Crypto', confidence: 68 },
  { symbol: 'MARA', name: 'Marathon Digital', sector: 'Crypto', confidence: 69 },
  { symbol: 'HUT', name: 'Hut 8 Mining Corp', sector: 'Crypto', confidence: 66 },
  { symbol: 'TLRY', name: 'Tilray Inc.', sector: 'Cannabis', confidence: 58 },
  { symbol: 'SNDL', name: 'Sundial Growers', sector: 'Cannabis', confidence: 56 },
  { symbol: 'CGC', name: 'Canopy Growth', sector: 'Cannabis', confidence: 62 },
  { symbol: 'ACB', name: 'Aurora Cannabis', sector: 'Cannabis', confidence: 55 },
  { symbol: 'PENN', name: 'Penn Entertainment', sector: 'Gaming', confidence: 68 },
  { symbol: 'MSGS', name: 'Madison Sq Garden', sector: 'Media', confidence: 69 },
  { symbol: 'DASH', name: 'DoorDash Inc.', sector: 'Consumer', confidence: 71 },
  { symbol: 'UBER', name: 'Uber Technologies', sector: 'Technology', confidence: 70 },
  { symbol: 'LYFT', name: 'Lyft Inc.', sector: 'Technology', confidence: 66 },
  { symbol: 'AIRB', name: 'Airbnb Inc.', sector: 'Consumer', confidence: 72 },
  { symbol: 'SPOT', name: 'Spotify Tech', sector: 'Media', confidence: 73 },
  { symbol: 'PINS', name: 'Pinterest Inc.', sector: 'Technology', confidence: 66 },
  { symbol: 'SNAP', name: 'Snap Inc.', sector: 'Technology', confidence: 64 },
  { symbol: 'ROKU', name: 'Roku Inc.', sector: 'Media', confidence: 67 },
  { symbol: 'SQ', name: 'Block Inc.', sector: 'Financial', confidence: 70 },
  { symbol: 'PYPL', name: 'PayPal Holdings', sector: 'Financial', confidence: 67 },
  { symbol: 'SHOP', name: 'Shopify Inc.', sector: 'Software', confidence: 71 },
  { symbol: 'UPST', name: 'Upstart Holdings', sector: 'Financial', confidence: 66 },
  { symbol: 'SNOW', name: 'Snowflake Inc.', sector: 'Software', confidence: 72 },
  { symbol: 'DBX', name: 'Dropbox Inc.', sector: 'Software', confidence: 65 },
  { symbol: 'DOCN', name: 'DigitalOcean', sector: 'Software', confidence: 64 },
  { symbol: 'CSGP', name: 'Corsair Gaming', sector: 'Consumer', confidence: 65 },
  { symbol: 'LOGI', name: 'Logitech Intl', sector: 'Consumer', confidence: 66 },
  { symbol: 'VRSN', name: 'Verisign Inc.', sector: 'Technology', confidence: 66 },
  { symbol: 'DNOW', name: 'DistributionNow', sector: 'Industrial', confidence: 64 },
  { symbol: 'GWW', name: 'Grainger Inc.', sector: 'Industrial', confidence: 69 },
  { symbol: 'SLG', name: 'SL Green Realty', sector: 'Real Estate', confidence: 62 },
  { symbol: 'VICI', name: 'VICI Properties', sector: 'Real Estate', confidence: 65 },
  { symbol: 'STAG', name: 'STAG Industrial', sector: 'Real Estate', confidence: 66 },
  { symbol: 'EQR', name: 'Equity Residential', sector: 'Real Estate', confidence: 65 },
  { symbol: 'AVB', name: 'AvalonBay Cmtys', sector: 'Real Estate', confidence: 67 },
];

export function searchAssets(query) {
  if (!query || query.length < 1) return [];
  const lower = query.toLowerCase();
  return EXPANDED_ASSETS.filter(asset =>
    asset.symbol.toLowerCase().includes(lower) ||
    asset.name.toLowerCase().includes(lower)
  ).slice(0, 50);
}

export function getAssetBySymbol(symbol) {
  return EXPANDED_ASSETS.find(a => a.symbol.toUpperCase() === symbol.toUpperCase());
}