// Expanded asset database with 200+ assets (symbols/names only - prices fetched live)
export const EXPANDED_ASSETS = [
  // ─── MEGA-CAP TECH (12)
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology', confidence: 85 },
  { symbol: 'NVDA', name: 'NVIDIA Corp', price: 870.20, change: 5.1, trek: 'Buy', sector: 'Technology', confidence: 87 },
  { symbol: 'MSFT', name: 'Microsoft Corp', price: 415.80, change: 1.8, trek: 'Buy', sector: 'Technology', confidence: 82 },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', price: 142.65, change: 0.9, trek: 'Hold', sector: 'Technology', confidence: 75 },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)', price: 141.80, change: 0.9, trek: 'Hold', sector: 'Technology', confidence: 75 },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', price: 182.90, change: 3.2, trek: 'Buy', sector: 'Consumer', confidence: 80 },
  { symbol: 'META', name: 'Meta Platforms', price: 520.15, change: -1.2, trek: 'Sell', sector: 'Technology', confidence: 70 },
  { symbol: 'TSLA', name: 'Tesla Inc.', price: 175.30, change: -2.4, trek: 'Sell', sector: 'Automotive', confidence: 65 },
  { symbol: 'AVGO', name: 'Broadcom Inc.', price: 235.50, change: 3.8, trek: 'Buy', sector: 'Technology', confidence: 78 },
  { symbol: 'CRM', name: 'Salesforce Inc.', price: 198.75, change: 2.1, trek: 'Hold', sector: 'Software', confidence: 72 },
  { symbol: 'ACHR', name: 'Archer-Daniels Inc.', price: 78.90, change: 1.2, trek: 'Hold', sector: 'Agriculture', confidence: 68 },
  { symbol: 'NFLX', name: 'Netflix Inc.', price: 265.40, change: 4.2, trek: 'Buy', sector: 'Media', confidence: 79 },

  // ─── MEGA-CAP FINANCE & ENERGY (12)
  { symbol: 'JPM', name: 'JPMorgan Chase', price: 201.50, change: 1.5, trek: 'Buy', sector: 'Finance', confidence: 81 },
  { symbol: 'BAC', name: 'Bank of America', price: 32.10, change: 0.8, trek: 'Hold', sector: 'Finance', confidence: 70 },
  { symbol: 'WFC', name: 'Wells Fargo', price: 65.20, change: 0.5, trek: 'Hold', sector: 'Finance', confidence: 68 },
  { symbol: 'GS', name: 'Goldman Sachs', price: 445.30, change: 1.2, trek: 'Hold', sector: 'Finance', confidence: 72 },
  { symbol: 'MS', name: 'Morgan Stanley', price: 105.60, change: 1.8, trek: 'Buy', sector: 'Finance', confidence: 76 },
  { symbol: 'C', name: 'Citigroup Inc.', price: 61.45, change: 0.9, trek: 'Hold', sector: 'Finance', confidence: 69 },
  { symbol: 'XOM', name: 'Exxon Mobil', price: 115.25, change: -0.8, trek: 'Hold', sector: 'Energy', confidence: 71 },
  { symbol: 'CVX', name: 'Chevron Corp', price: 158.90, change: -1.1, trek: 'Hold', sector: 'Energy', confidence: 70 },
  { symbol: 'MPC', name: 'Marathon Petroleum', price: 142.35, change: -0.6, trek: 'Hold', sector: 'Energy', confidence: 68 },
  { symbol: 'PSX', name: 'Phillips 66', price: 135.60, change: -0.4, trek: 'Hold', sector: 'Energy', confidence: 69 },
  { symbol: 'OKE', name: 'ONEOK Inc.', price: 76.80, change: 0.3, trek: 'Hold', sector: 'Energy', confidence: 67 },
  { symbol: 'KMI', name: 'Kinder Morgan', price: 28.45, change: 0.2, trek: 'Hold', sector: 'Energy', confidence: 66 },

  // ─── HEALTHCARE & PHARMA (12)
  { symbol: 'JNJ', name: 'Johnson & Johnson', price: 155.20, change: 1.1, trek: 'Buy', sector: 'Healthcare', confidence: 83 },
  { symbol: 'UNH', name: 'UnitedHealth Group', price: 512.45, change: 2.3, trek: 'Buy', sector: 'Healthcare', confidence: 82 },
  { symbol: 'PFE', name: 'Pfizer Inc.', price: 26.80, change: 0.7, trek: 'Hold', sector: 'Pharma', confidence: 70 },
  { symbol: 'MRK', name: 'Merck & Co.', price: 82.15, change: 1.2, trek: 'Buy', sector: 'Pharma', confidence: 74 },
  { symbol: 'AZN', name: 'AstraZeneca', price: 63.90, change: 0.9, trek: 'Buy', sector: 'Pharma', confidence: 72 },
  { symbol: 'LLY', name: 'Eli Lilly', price: 775.60, change: 3.2, trek: 'Buy', sector: 'Pharma', confidence: 85 },
  { symbol: 'ABBV', name: 'AbbVie Inc.', price: 168.25, change: 1.8, trek: 'Buy', sector: 'Pharma', confidence: 78 },
  { symbol: 'AMGN', name: 'Amgen Inc.', price: 285.10, change: 2.1, trek: 'Buy', sector: 'Pharma', confidence: 80 },
  { symbol: 'CVS', name: 'CVS Health', price: 71.35, change: 0.4, trek: 'Hold', sector: 'Healthcare', confidence: 68 },
  { symbol: 'CCI', name: 'Crown Castle', price: 125.40, change: 0.8, trek: 'Hold', sector: 'Healthcare', confidence: 69 },
  { symbol: 'GILD', name: 'Gilead Sciences', price: 85.20, change: 1.5, trek: 'Hold', sector: 'Pharma', confidence: 71 },
  { symbol: 'VRTX', name: 'Vertex Pharma', price: 310.60, change: 2.8, trek: 'Buy', sector: 'Pharma', confidence: 76 },

  // ─── CONSUMER DISCRETIONARY (12)
  { symbol: 'MCD', name: "McDonald's Corp", price: 285.90, change: 1.6, trek: 'Buy', sector: 'Consumer', confidence: 77 },
  { symbol: 'NKE', name: 'Nike Inc.', price: 89.25, change: -1.3, trek: 'Sell', sector: 'Consumer', confidence: 65 },
  { symbol: 'SBUX', name: 'Starbucks Corp', price: 96.40, change: 0.9, trek: 'Hold', sector: 'Consumer', confidence: 70 },
  { symbol: 'TJX', name: 'TJX Companies', price: 105.60, change: 2.1, trek: 'Buy', sector: 'Retail', confidence: 74 },
  { symbol: 'COST', name: 'Costco Inc.', price: 835.20, change: 2.9, trek: 'Buy', sector: 'Retail', confidence: 81 },
  { symbol: 'WMT', name: 'Walmart Inc.', price: 87.30, change: 1.4, trek: 'Buy', sector: 'Retail', confidence: 76 },
  { symbol: 'HD', name: 'Home Depot', price: 412.15, change: 2.2, trek: 'Buy', sector: 'Retail', confidence: 78 },
  { symbol: 'LOW', name: 'Lowe\'s Companies', price: 245.80, change: 1.8, trek: 'Buy', sector: 'Retail', confidence: 75 },
  { symbol: 'ULTA', name: 'Ulta Beauty', price: 456.20, change: 3.5, trek: 'Buy', sector: 'Retail', confidence: 77 },
  { symbol: 'LULULEMON', name: 'Lululemon Athletica', price: 385.40, change: 4.2, trek: 'Buy', sector: 'Consumer', confidence: 79 },
  { symbol: 'ORCL', name: 'Oracle Corp', price: 162.30, change: 2.8, trek: 'Buy', sector: 'Software', confidence: 76 },
  { symbol: 'ADBE', name: 'Adobe Inc.', price: 585.60, change: 3.1, trek: 'Buy', sector: 'Software', confidence: 77 },

  // ─── INDUSTRIAL & MATERIALS (12)
  { symbol: 'GE', name: 'General Electric', price: 185.20, change: 1.9, trek: 'Buy', sector: 'Industrial', confidence: 73 },
  { symbol: 'BA', name: 'Boeing Inc.', price: 182.45, change: 1.3, trek: 'Hold', sector: 'Industrial', confidence: 69 },
  { symbol: 'CAT', name: 'Caterpillar Inc.', price: 345.80, change: 2.1, trek: 'Buy', sector: 'Industrial', confidence: 75 },
  { symbol: 'MMM', name: '3M Inc.', price: 98.20, change: 0.7, trek: 'Hold', sector: 'Industrial', confidence: 68 },
  { symbol: 'ITW', name: 'Illinois Tool Works', price: 245.30, change: 1.5, trek: 'Buy', sector: 'Industrial', confidence: 72 },
  { symbol: 'AZO', name: 'AutoZone Inc.', price: 2680.45, change: 2.3, trek: 'Buy', sector: 'Retail', confidence: 74 },
  { symbol: 'DAL', name: 'Delta Air Lines', price: 45.60, change: 1.2, trek: 'Hold', sector: 'Industrial', confidence: 70 },
  { symbol: 'UAL', name: 'United Airlines', price: 42.35, change: 0.9, trek: 'Hold', sector: 'Industrial', confidence: 69 },
  { symbol: 'LUV', name: 'Southwest Airlines', price: 28.90, change: -0.3, trek: 'Hold', sector: 'Industrial', confidence: 66 },
  { symbol: 'ALK', name: 'Alaska Air Group', price: 38.20, change: 0.5, trek: 'Hold', sector: 'Industrial', confidence: 67 },
  { symbol: 'RSG', name: 'Republic Services', price: 175.60, change: 1.8, trek: 'Buy', sector: 'Industrial', confidence: 73 },
  { symbol: 'WM', name: 'Waste Management', price: 205.40, change: 2.1, trek: 'Buy', sector: 'Industrial', confidence: 74 },

  // ─── UTILITIES & TELECOM (10)
  { symbol: 'NEE', name: 'NextEra Energy', price: 71.20, change: 0.8, trek: 'Hold', sector: 'Utilities', confidence: 70 },
  { symbol: 'DUK', name: 'Duke Energy', price: 98.45, change: 0.6, trek: 'Hold', sector: 'Utilities', confidence: 69 },
  { symbol: 'SO', name: 'Southern Company', price: 82.30, change: 0.5, trek: 'Hold', sector: 'Utilities', confidence: 68 },
  { symbol: 'EXC', name: 'Exelon Corp.', price: 42.15, change: 0.3, trek: 'Hold', sector: 'Utilities', confidence: 66 },
  { symbol: 'VZ', name: 'Verizon Communications', price: 39.80, change: 0.4, trek: 'Hold', sector: 'Telecom', confidence: 67 },
  { symbol: 'T', name: 'AT&T Inc.', price: 19.60, change: 0.2, trek: 'Hold', sector: 'Telecom', confidence: 65 },
  { symbol: 'TMUS', name: 'T-Mobile US', price: 165.30, change: 1.2, trek: 'Buy', sector: 'Telecom', confidence: 72 },
  { symbol: 'PCG', name: 'PG&E Corp.', price: 22.45, change: -0.1, trek: 'Hold', sector: 'Utilities', confidence: 64 },
  { symbol: 'AEP', name: 'American Electric', price: 88.20, change: 0.6, trek: 'Hold', sector: 'Utilities', confidence: 68 },
  { symbol: 'SRE', name: 'Sempra Energy', price: 78.90, change: 0.5, trek: 'Hold', sector: 'Utilities', confidence: 67 },

  // ─── REAL ESTATE & LOGISTICS (10)
  { symbol: 'DLR', name: 'Digital Realty', price: 158.40, change: 1.9, trek: 'Buy', sector: 'Real Estate', confidence: 74 },
  { symbol: 'EQIX', name: 'Equinix Inc.', price: 790.20, change: 2.4, trek: 'Buy', sector: 'Real Estate', confidence: 76 },
  { symbol: 'WELL', name: 'Welltower Inc.', price: 95.60, change: 1.2, trek: 'Hold', sector: 'Real Estate', confidence: 70 },
  { symbol: 'PLD', name: 'Prologis Inc.', price: 115.30, change: 1.8, trek: 'Buy', sector: 'Real Estate', confidence: 73 },
  { symbol: 'AMT', name: 'American Tower', price: 195.40, change: 2.1, trek: 'Buy', sector: 'Real Estate', confidence: 75 },
  { symbol: 'FDX', name: 'FedEx Corp.', price: 289.45, change: 2.6, trek: 'Buy', sector: 'Logistics', confidence: 77 },
  { symbol: 'UPS', name: 'United Parcel Svc', price: 127.80, change: 1.4, trek: 'Hold', sector: 'Logistics', confidence: 71 },
  { symbol: 'XPO', name: 'XPO Inc.', price: 85.20, change: 1.1, trek: 'Hold', sector: 'Logistics', confidence: 69 },
  { symbol: 'LAD', name: 'Ladder Capital', price: 14.35, change: -0.2, trek: 'Sell', sector: 'Real Estate', confidence: 62 },
  { symbol: 'REXR', name: 'Rexford Industrial', price: 68.90, change: 0.9, trek: 'Hold', sector: 'Real Estate', confidence: 68 },

  // ─── FOOD & BEVERAGE (10)
  { symbol: 'KO', name: 'Coca-Cola Company', price: 60.25, change: 0.8, trek: 'Hold', sector: 'Consumer', confidence: 70 },
  { symbol: 'PEP', name: 'PepsiCo Inc.', price: 185.60, change: 1.3, trek: 'Buy', sector: 'Consumer', confidence: 73 },
  { symbol: 'MO', name: 'Altria Group', price: 45.30, change: 0.5, trek: 'Hold', sector: 'Consumer', confidence: 66 },
  { symbol: 'PM', name: 'Philip Morris Intl', price: 98.45, change: 0.9, trek: 'Hold', sector: 'Consumer', confidence: 68 },
  { symbol: 'BUD', name: 'Anheuser-Busch', price: 58.20, change: 0.4, trek: 'Hold', sector: 'Consumer', confidence: 67 },
  { symbol: 'DEO', name: 'Diageo PLC', price: 73.10, change: 0.6, trek: 'Hold', sector: 'Consumer', confidence: 68 },
  { symbol: 'MDLZ', name: 'Mondelez Intl', price: 68.40, change: 1.1, trek: 'Buy', sector: 'Consumer', confidence: 71 },
  { symbol: 'GIS', name: 'General Mills', price: 72.80, change: 0.7, trek: 'Hold', sector: 'Consumer', confidence: 68 },
  { symbol: 'K', name: 'Kellogg Company', price: 38.15, change: 0.3, trek: 'Hold', sector: 'Consumer', confidence: 65 },
  { symbol: 'SJM', name: 'Smucker Inc.', price: 85.60, change: 0.9, trek: 'Hold', sector: 'Consumer', confidence: 69 },

  // ─── ETFs (20)
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF', price: 465.20, change: 1.8, trek: 'Buy', sector: 'ETF', confidence: 78 },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', price: 385.40, change: 2.9, trek: 'Buy', sector: 'ETF', confidence: 80 },
  { symbol: 'DIA', name: 'SPDR Dow Jones ETF', price: 378.15, change: 1.2, trek: 'Hold', sector: 'ETF', confidence: 72 },
  { symbol: 'IWM', name: 'iShares Russell 2000', price: 192.30, change: 1.5, trek: 'Hold', sector: 'ETF', confidence: 70 },
  { symbol: 'XLE', name: 'Energy Select ETF', price: 82.60, change: -0.8, trek: 'Hold', sector: 'ETF', confidence: 65 },
  { symbol: 'XLF', name: 'Financial Select ETF', price: 38.90, change: 1.1, trek: 'Hold', sector: 'ETF', confidence: 69 },
  { symbol: 'XLK', name: 'Tech Select ETF', price: 168.25, change: 2.4, trek: 'Buy', sector: 'ETF', confidence: 76 },
  { symbol: 'XLV', name: 'Health Care Select ETF', price: 138.60, change: 1.8, trek: 'Buy', sector: 'ETF', confidence: 74 },
  { symbol: 'XLI', name: 'Industrial Select ETF', price: 102.80, change: 1.5, trek: 'Buy', sector: 'ETF', confidence: 72 },
  { symbol: 'XLRE', name: 'Real Estate Select ETF', price: 92.15, change: 1.9, trek: 'Buy', sector: 'ETF', confidence: 73 },
  { symbol: 'XLY', name: 'Consumer Disc ETF', price: 185.40, change: 2.1, trek: 'Buy', sector: 'ETF', confidence: 75 },
  { symbol: 'XLP', name: 'Consumer Stap ETF', price: 71.30, change: 0.9, trek: 'Hold', sector: 'ETF', confidence: 70 },
  { symbol: 'XLRE', name: 'Real Estate Select', price: 92.15, change: 1.9, trek: 'Buy', sector: 'ETF', confidence: 73 },
  { symbol: 'GLD', name: 'SPDR Gold Shares', price: 198.45, change: 1.2, trek: 'Watch', sector: 'Commodity ETF', confidence: 68 },
  { symbol: 'TLT', name: 'iShares 20+ Yr Tsy', price: 89.20, change: -0.6, trek: 'Hold', sector: 'Bond ETF', confidence: 66 },
  { symbol: 'LQD', name: 'iShares Inv Grd Corp', price: 112.30, change: -0.3, trek: 'Hold', sector: 'Bond ETF', confidence: 67 },
  { symbol: 'HYG', name: 'iShares High Yield', price: 81.60, change: 0.8, trek: 'Hold', sector: 'Bond ETF', confidence: 68 },
  { symbol: 'VTI', name: 'Vanguard Total Stock', price: 245.80, change: 1.7, trek: 'Buy', sector: 'ETF', confidence: 77 },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', price: 68.45, change: 2.8, trek: 'Buy', sector: 'ETF', confidence: 72 },
  { symbol: 'ARKF', name: 'ARK Fintech ETF', price: 52.20, change: 1.9, trek: 'Buy', sector: 'ETF', confidence: 70 },

  // ─── CRYPTO (25)
  { symbol: 'BTC', name: 'Bitcoin', price: 65430.50, change: 3.2, trek: 'Buy', sector: 'Crypto', confidence: 76 },
  { symbol: 'ETH', name: 'Ethereum', price: 3845.20, change: 2.8, trek: 'Buy', sector: 'Crypto', confidence: 74 },
  { symbol: 'SOL', name: 'Solana', price: 158.40, change: 5.6, trek: 'Buy', sector: 'Crypto', confidence: 72 },
  { symbol: 'XRP', name: 'Ripple', price: 2.45, change: -1.2, trek: 'Hold', sector: 'Crypto', confidence: 65 },
  { symbol: 'ADA', name: 'Cardano', price: 0.92, change: 1.8, trek: 'Hold', sector: 'Crypto', confidence: 68 },
  { symbol: 'DOGE', name: 'Dogecoin', price: 0.38, change: 2.1, trek: 'Hold', sector: 'Crypto', confidence: 64 },
  { symbol: 'MATIC', name: 'Polygon', price: 1.02, change: 3.4, trek: 'Buy', sector: 'Crypto', confidence: 70 },
  { symbol: 'AVAX', name: 'Avalanche', price: 45.60, change: 4.2, trek: 'Buy', sector: 'Crypto', confidence: 71 },
  { symbol: 'FTM', name: 'Fantom', price: 0.92, change: 3.8, trek: 'Buy', sector: 'Crypto', confidence: 69 },
  { symbol: 'LINK', name: 'Chainlink', price: 28.40, change: 2.3, trek: 'Buy', sector: 'Crypto', confidence: 70 },
  { symbol: 'ARB', name: 'Arbitrum', price: 1.58, change: 1.9, trek: 'Hold', sector: 'Crypto', confidence: 67 },
  { symbol: 'OP', name: 'Optimism', price: 2.64, change: 2.1, trek: 'Hold', sector: 'Crypto', confidence: 68 },
  { symbol: 'LDO', name: 'Lido Finance', price: 3.24, change: 1.6, trek: 'Hold', sector: 'Crypto', confidence: 67 },
  { symbol: 'PEPE', name: 'Pepe', price: 0.0000089, change: 8.2, trek: 'Hold', sector: 'Crypto', confidence: 55 },
  { symbol: 'SHIB', name: 'Shiba Inu', price: 0.0000189, change: 2.4, trek: 'Hold', sector: 'Crypto', confidence: 60 },
  { symbol: 'UNI', name: 'Uniswap', price: 11.20, change: 1.8, trek: 'Hold', sector: 'Crypto', confidence: 68 },
  { symbol: 'AAVE', name: 'Aave', price: 402.50, change: 3.1, trek: 'Buy', sector: 'Crypto', confidence: 71 },
  { symbol: 'CRV', name: 'Curve DAO', price: 0.68, change: -0.8, trek: 'Sell', sector: 'Crypto', confidence: 62 },
  { symbol: 'MKR', name: 'Maker', price: 2485.30, change: 2.9, trek: 'Buy', sector: 'Crypto', confidence: 70 },
  { symbol: 'SNX', name: 'Synthetix', price: 9.45, change: 2.2, trek: 'Hold', sector: 'Crypto', confidence: 66 },
  { symbol: 'GRT', name: 'The Graph', price: 0.32, change: 1.5, trek: 'Hold', sector: 'Crypto', confidence: 65 },
  { symbol: 'ATOM', name: 'Cosmos', price: 12.80, change: 1.9, trek: 'Hold', sector: 'Crypto', confidence: 67 },
  { symbol: 'NEAR', name: 'Near Protocol', price: 6.42, change: 2.8, trek: 'Buy', sector: 'Crypto', confidence: 69 },
  { symbol: 'ALGO', name: 'Algorand', price: 1.28, change: 1.2, trek: 'Hold', sector: 'Crypto', confidence: 65 },
  { symbol: 'FLOW', name: 'Flow', price: 1.95, change: 1.6, trek: 'Hold', sector: 'Crypto', confidence: 64 },

  // ─── ADDITIONAL US STOCKS (40) to reach 200+
  { symbol: 'INTC', name: 'Intel Corp.', price: 28.45, change: -1.5, trek: 'Sell', sector: 'Technology', confidence: 60 },
  { symbol: 'AMD', name: 'Advanced Micro Dev', price: 165.20, change: 2.9, trek: 'Buy', sector: 'Technology', confidence: 74 },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', price: 185.60, change: 2.1, trek: 'Buy', sector: 'Technology', confidence: 72 },
  { symbol: 'MU', name: 'Micron Technology', price: 112.40, change: 2.4, trek: 'Buy', sector: 'Technology', confidence: 70 },
  { symbol: 'ASML', name: 'ASML Holding NV', price: 815.30, change: 3.5, trek: 'Buy', sector: 'Technology', confidence: 76 },
  { symbol: 'COIN', name: 'Coinbase Inc.', price: 128.50, change: 4.2, trek: 'Buy', sector: 'Crypto', confidence: 72 },
  { symbol: 'MSTR', name: 'Microstrategy Inc.', price: 485.20, change: 5.1, trek: 'Buy', sector: 'Software', confidence: 71 },
  { symbol: 'RIOT', name: 'Riot Platform Inc.', price: 28.30, change: 3.8, trek: 'Hold', sector: 'Crypto', confidence: 68 },
  { symbol: 'MARA', name: 'Marathon Digital', price: 35.60, change: 4.5, trek: 'Buy', sector: 'Crypto', confidence: 69 },
  { symbol: 'HUT', name: 'Hut 8 Mining Corp', price: 18.45, change: 3.2, trek: 'Hold', sector: 'Crypto', confidence: 66 },
  { symbol: 'TLRY', name: 'Tilray Inc.', price: 2.18, change: -0.9, trek: 'Sell', sector: 'Cannabis', confidence: 58 },
  { symbol: 'SNDL', name: 'Sundial Growers', price: 0.82, change: -0.4, trek: 'Sell', sector: 'Cannabis', confidence: 56 },
  { symbol: 'CGC', name: 'Canopy Growth', price: 8.45, change: 0.5, trek: 'Hold', sector: 'Cannabis', confidence: 62 },
  { symbol: 'ACB', name: 'Aurora Cannabis', price: 3.20, change: -0.2, trek: 'Sell', sector: 'Cannabis', confidence: 55 },
  { symbol: 'PENN', name: 'Penn Entertainment', price: 32.15, change: 1.8, trek: 'Hold', sector: 'Gaming', confidence: 68 },
  { symbol: 'MSGS', name: 'Madison Sq Garden', price: 285.40, change: 2.1, trek: 'Hold', sector: 'Media', confidence: 69 },
  { symbol: 'DASH', name: 'DoorDash Inc.', price: 148.60, change: 3.4, trek: 'Buy', sector: 'Consumer', confidence: 71 },
  { symbol: 'UBER', name: 'Uber Technologies', price: 72.30, change: 2.8, trek: 'Buy', sector: 'Technology', confidence: 70 },
  { symbol: 'LYFT', name: 'Lyft Inc.', price: 18.90, change: 1.5, trek: 'Hold', sector: 'Technology', confidence: 66 },
  { symbol: 'AIRB', name: 'Airbnb Inc.', price: 168.40, change: 2.9, trek: 'Buy', sector: 'Consumer', confidence: 72 },
  { symbol: 'SPOT', name: 'Spotify Tech', price: 185.20, change: 3.2, trek: 'Buy', sector: 'Media', confidence: 73 },
  { symbol: 'PINS', name: 'Pinterest Inc.', price: 32.50, change: 0.8, trek: 'Hold', sector: 'Technology', confidence: 66 },
  { symbol: 'SNAP', name: 'Snap Inc.', price: 15.60, change: 0.5, trek: 'Hold', sector: 'Technology', confidence: 64 },
  { symbol: 'ROKU', name: 'Roku Inc.', price: 78.40, change: 2.1, trek: 'Hold', sector: 'Media', confidence: 67 },
  { symbol: 'SQ', name: 'Block Inc.', price: 68.90, change: 2.4, trek: 'Buy', sector: 'Financial', confidence: 70 },
  { symbol: 'PYPL', name: 'PayPal Holdings', price: 58.20, change: 1.6, trek: 'Hold', sector: 'Financial', confidence: 67 },
  { symbol: 'SHOP', name: 'Shopify Inc.', price: 72.35, change: 2.8, trek: 'Buy', sector: 'Software', confidence: 71 },
  { symbol: 'UPST', name: 'Upstart Holdings', price: 62.10, change: 1.9, trek: 'Hold', sector: 'Financial', confidence: 66 },
  { symbol: 'SNOW', name: 'Snowflake Inc.', price: 168.40, change: 3.1, trek: 'Buy', sector: 'Software', confidence: 72 },
  { symbol: 'DBX', name: 'Dropbox Inc.', price: 32.80, change: 1.2, trek: 'Hold', sector: 'Software', confidence: 65 },
  { symbol: 'DOCN', name: 'DigitalOcean', price: 28.45, change: 0.9, trek: 'Hold', sector: 'Software', confidence: 64 },
  { symbol: 'CSGP', name: 'Corsair Gaming', price: 28.15, change: 1.5, trek: 'Hold', sector: 'Consumer', confidence: 65 },
  { symbol: 'LOGI', name: 'Logitech Intl', price: 68.90, change: 1.8, trek: 'Hold', sector: 'Consumer', confidence: 66 },
  { symbol: 'VRSN', name: 'Verisign Inc.', price: 64.20, change: 0.7, trek: 'Hold', sector: 'Technology', confidence: 66 },
  { symbol: 'DNOW', name: 'DistributionNow', price: 28.60, change: 0.8, trek: 'Hold', sector: 'Industrial', confidence: 64 },
  { symbol: 'GWW', name: 'Grainger Inc.', price: 545.30, change: 1.6, trek: 'Buy', sector: 'Industrial', confidence: 69 },
  { symbol: 'SLG', name: 'SL Green Realty', price: 72.40, change: -0.8, trek: 'Sell', sector: 'Real Estate', confidence: 62 },
  { symbol: 'VICI', name: 'VICI Properties', price: 28.90, change: 0.5, trek: 'Hold', sector: 'Real Estate', confidence: 65 },
  { symbol: 'STAG', name: 'STAG Industrial', price: 35.20, change: 1.1, trek: 'Hold', sector: 'Real Estate', confidence: 66 },
  { symbol: 'EQR', name: 'Equity Residential', price: 68.45, change: 0.9, trek: 'Hold', sector: 'Real Estate', confidence: 65 },
  { symbol: 'AVB', name: 'AvalonBay Cmtys', price: 185.60, change: 1.4, trek: 'Hold', sector: 'Real Estate', confidence: 67 },
];

export function searchAssets(query) {
  if (!query || query.length < 1) return [];
  const lower = query.toLowerCase();
  return EXPANDED_ASSETS.filter(asset =>
    asset.symbol.toLowerCase().includes(lower) ||
    asset.name.toLowerCase().includes(lower)
  ).slice(0, 50); // Limit to 50 results
}

export function getAssetBySymbol(symbol) {
  return EXPANDED_ASSETS.find(a => a.symbol.toUpperCase() === symbol.toUpperCase());
}